### ISSUE TITLE
Drop Python 2.7 support

### ISSUE THREAD

**Issue by agermanidis** [runwayml/model-sdk#49]
I've become increasingly convinced that we should drop support for Python 2.7. My main reasons would be that it will allow us we can use an [asyncio](https://docs.python.org/3/library/asyncio.html)-based library such as [aiohttp](https://aiohttp.readthedocs.io/en/stable/) as the HTTP server backbone, and it will also enable us to utilize static type checking, which would get especially handy as we add support for more data types and the cognitive load of remembering how to work with them increases.  We're only using a Python 2 environment in 3 out of the 20 models we have in the platform (AttnGAN, Visual Importance, DensePose), and even those can be migrated to Python 3 with little effort. Plus, [Python 2 reaches EOL in 2020](https://pythonclock.org/). Better to make the transition now than later!

**Comment by clankill3r** [comment]
do it!
