### ISSUE TITLE
runway.setup with empty options gives unexpected error

### ISSUE THREAD

**Issue by aparrish** [runwayml/model-sdk#63]
I was trying to make a very minimal Runway model and noticed that if the `options` parameter to the `setup` decorator is an empty dictionary, you get a runtime error. Here's minimal code to reproduce:

```
import runway                                                                   
                                                                                
@runway.setup(options={})                                                       
def setup(opts):                                                                
    return "hello"                                                              
                                                                                
if __name__ == '__main__':                                                      
    runway.run(host='0.0.0.0', port=8000)
```

... which produces (for me) the following error:

```
Error during setup: TypeError("setup() missing 1 required positional argument: 'opts'",).
File "/Users/allison/anaconda/lib/python3.6/site-packages/runway/model.py", line 455, in run
    self.setup_model(model_options)
File "/Users/allison/anaconda/lib/python3.6/site-packages/runway/model.py", line 337, in setup_model
    raise reraise(SetupError, SetupError(repr(err)), sys.exc_info()[2])
File "/Users/allison/anaconda/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
File "/Users/allison/anaconda/lib/python3.6/site-packages/runway/model.py", line 335, in setup_model
    self.model = self.setup_fn()
```

This is on Python 3.6, using version 0.0.75 of Runway SDK.

I think the problem is here:

https://github.com/runwayml/model-sdk/blob/14b36a2e749e76cf8c555363dceaa01fac39902d/runway/model.py#L317

... because `self.options` is an empty array, it counts as False-y in the `if` statement, which  causes the `elif` below to run (which in turn calls the setup function without any parameters).

(This came up when I was trying to prune down the example `runway_model.py` in the `model-template` directory to a bare minimum—I wasn't sure how the `options` parameter worked, so I just deleted the keys/values from the dictionary literal in the hopes that I would end up with a model that didn't have any options. I see now that `@model.setup` [w/o parameters] is how you'd be expected to use the decorator in the situation. So not a show-stopping bug, but might be confusing to other future developers like it was for me)

**Comment by agermanidis** [comment]
Thanks for catching this! The behavior of setup with no arguments has been the source of confusion for others as well, I'll have a PR up to fix this shortly.

**Comment by brannondorsey** [comment]
We have very little parameter validation in the Model SDK right now, which is not ideal. This is something we should address, so thanks for reporting it!
