### ISSUE TITLE
Set up an own remote gpu

### ISSUE THREAD

**Issue by clankill3r** [runwayml/model-sdk#69]
Hi,
it seems really likely that the students of our art academy will be using runway next semester.
I would really like to set up a own or multiple remote gpu(s) that students are able to use.
Is such a thing possible? Or will it eventually be possible?

**Comment by cvalenzuela** [comment]
Hey @clankill3r! Happy to help you and your students use Runway. Let's follow up this conversation via email? Can you send me an email to cris@runwayml.com?

Thanks!
